doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  types:
    domain_uuid: 'App\Shared\Infrastructure\DoctrineType\DomainUuidType'
    oauth2_scope: 'App\OAuth\Infrastructure\DoctrineType\OAuth2ScopeType'
    oauth2_grant: 'App\OAuth\Infrastructure\DoctrineType\OAuth2GrantType'
    oauth2_redirect_uri: 'App\OAuth\Infrastructure\DoctrineType\OAuth2RedirectUriType'
  connections:
    default:
      server: '%env(MONGODB_URL)%'
      options: {}
  document_managers:
    default:
      auto_mapping: true
      mappings:
        User:
          is_bundle: false
          type: xml
          dir: '%kernel.project_dir%/config/doctrine/User'
          prefix: 'App\User\Domain\Entity'
          alias: User
        OAuth:
          is_bundle: false
          type: xml
          dir: '%kernel.project_dir%/config/doctrine/OAuth'
          prefix: 'League\Bundle\OAuth2ServerBundle\Model'
          alias: OAuth
