doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  types:
    domain_uuid: 'App\Shared\Infrastructure\DoctrineType\DomainUuidType'
  connections:
    default:
      server: '%env(MONGODB_URL)%'
      options: {}
  document_managers:
    default:
      auto_mapping: true
      mappings:
        User:
          is_bundle: false
          type: xml
          dir: '%kernel.project_dir%/config/doctrine'
          prefix: 'App\User\Domain\Entity'
          alias: User
