framework:
  rate_limiter:
    password_reset:
      policy: 'token_bucket'
      limit: '%env(int:PASSWORD_RESET_RATE_LIMIT_MAX_REQUESTS)%'
      rate: { interval: '%env(string:PASSWORD_RESET_RATE_LIMIT_INTERVAL)%' }
      cache_pool: 'cache.app'
